<<<<<<< HEAD
// Artfolio images distributed across 3 columns for infinite asymmetric scroll.
// This manifest only includes files that exist in artfolio_images/.
const GALLERY_IMAGES = [
  "img1.png",
  "img2.png",
  "img3.png",
  "img4.png",
  "image_12.jpeg",
  "image_13.jpeg",
  "image_19.png",
  "image_20.png",
  "image_21.png",
  "image_25.jpeg",
  "image_26.png",
  "image_27.png",
  "image_28.png",
  "image_31.jpeg",
  "image_32.jpeg",
  "image_33.jpeg",
  "image_34.jpeg",
  "image_35.jpeg",
  "image_36.jpeg",
  "image_37.jpeg",
  "image_38.jpeg",
  "image_39.jpeg",
  "image_43.jpeg",
  "image_44.jpeg",
  "image_45.jpeg",
  "image_46.png",
  "image_48.png",
  "image_49.jpeg",
  "image_50.jpeg",
  "image_51.jpeg",
  "image_52.png",
  "image_53.jpeg",
  "image_54.jpeg",
  "image_55.jpeg",
  "image_56.jpeg",
  "image_57.jpeg",
  "image_58.jpeg",
  "image_59.jpeg",
  "image_60.jpeg",
  "image_62.jpeg",
  "image_64.png",
  "image_65.png",
  "image_66.png",
  "image_67.png",
  "image_68.png",
  "image_69.jpeg",
  "image_70.png",
  "image_71.png",
  "image_78.png",
  "image_80.png",
  "image_81.png",
  "image_82.png",
  "image_84.png",
  "image_85.png",
  "image_87.png",
  "image_91.jpeg",
  "image_93.png",
  "image_96.jpeg",
  "image_98.png",
  "image_102.png",
  "image_105.png",
  "image_107.jpeg",
  "image_113.jpeg",
  "image_114.png",
  "image_128.jpeg",
  "image_129.jpeg",
  "image_130.jpeg",
  "image_131.jpeg",
  "image_132.jpeg",
  "image_133.jpeg",
  "image_135.jpeg",
  "image_137.jpeg",
  "image_138.jpeg",
  "image_139.jpeg",
  "image_140.jpeg",
  "image_141.jpeg",
  "image_142.jpeg",
  "image_143.jpeg",
  "image_145.png",
  "image_146.png",
  "image_147.png",
  "image_148.png",
  "image_149.png",
  "image_151.png",
  "image_152.png",
  "image_153.png",
  "image_154.png",
  "image_155.png",
  "image_156.jpeg",
  "image_157.jpeg",
  "image_158.jpeg",
  "image_159.jpeg",
  "image_160.jpeg",
  "image_161.jpeg",
  "image_162.jpeg",
  "image_163.jpeg",
  "image_164.jpeg",
  "image_165.jpeg",
  "image_166.jpeg",
  "image_167.jpeg",
  "image_168.png",
  "image_169.png",
  "image_170.png",
  "image_171.png",
  "image_172.jpeg",
  "image_174.jpeg",
  "image_176.jpeg",
  "image_177.jpeg",
  "image_178.jpeg",
  "image_179.jpeg",
  "image_180.jpeg",
  "image_182.jpeg",
  "image_195.jpeg",
  "image_196.jpeg",
  "image_198.jpeg",
  "image_201.jpeg",
];

const LABELS = ["Art", "Design", "Visual", "Work"];

function buildColumns(images, columnCount) {
  const columns = Array.from({ length: columnCount }, () => []);
  const baseSize = Math.floor(images.length / columnCount);
  const remainder = images.length % columnCount;
  let imageIndex = 0;

  for (let columnIndex = 0; columnIndex < columnCount; columnIndex++) {
    const columnSize = baseSize + (columnIndex < remainder ? 1 : 0);

    for (let offset = 0; offset < columnSize; offset++) {
      const fileName = images[imageIndex++];
      columns[columnIndex].push({
        src: `artfolio_images/${fileName}`,
        label: LABELS[(imageIndex - 1) % LABELS.length],
      });
    }
  }

  return columns;
}

=======
// Artfolio images distributed across 3 columns for infinite asymmetric scroll.
// This manifest only includes files that exist in artfolio_images/.
const GALLERY_IMAGES = [
  "img1.png",
  "img2.png",
  "img3.png",
  "img4.png",
  "image_12.jpeg",
  "image_13.jpeg",
  "image_19.png",
  "image_20.png",
  "image_21.png",
  "image_25.jpeg",
  "image_26.png",
  "image_27.png",
  "image_28.png",
  "image_31.jpeg",
  "image_32.jpeg",
  "image_33.jpeg",
  "image_34.jpeg",
  "image_35.jpeg",
  "image_36.jpeg",
  "image_37.jpeg",
  "image_38.jpeg",
  "image_39.jpeg",
  "image_43.jpeg",
  "image_44.jpeg",
  "image_45.jpeg",
  "image_46.png",
  "image_48.png",
  "image_49.jpeg",
  "image_50.jpeg",
  "image_51.jpeg",
  "image_52.png",
  "image_53.jpeg",
  "image_54.jpeg",
  "image_55.jpeg",
  "image_56.jpeg",
  "image_57.jpeg",
  "image_58.jpeg",
  "image_59.jpeg",
  "image_60.jpeg",
  "image_62.jpeg",
  "image_64.png",
  "image_65.png",
  "image_66.png",
  "image_67.png",
  "image_68.png",
  "image_69.jpeg",
  "image_70.png",
  "image_71.png",
  "image_78.png",
  "image_80.png",
  "image_81.png",
  "image_82.png",
  "image_84.png",
  "image_85.png",
  "image_87.png",
  "image_91.jpeg",
  "image_93.png",
  "image_96.jpeg",
  "image_98.png",
  "image_102.png",
  "image_105.png",
  "image_107.jpeg",
  "image_113.jpeg",
  "image_114.png",
  "image_128.jpeg",
  "image_129.jpeg",
  "image_130.jpeg",
  "image_131.jpeg",
  "image_132.jpeg",
  "image_133.jpeg",
  "image_135.jpeg",
  "image_137.jpeg",
  "image_138.jpeg",
  "image_139.jpeg",
  "image_140.jpeg",
  "image_141.jpeg",
  "image_142.jpeg",
  "image_143.jpeg",
  "image_145.png",
  "image_146.png",
  "image_147.png",
  "image_148.png",
  "image_149.png",
  "image_151.png",
  "image_152.png",
  "image_153.png",
  "image_154.png",
  "image_155.png",
  "image_156.jpeg",
  "image_157.jpeg",
  "image_158.jpeg",
  "image_159.jpeg",
  "image_160.jpeg",
  "image_161.jpeg",
  "image_162.jpeg",
  "image_163.jpeg",
  "image_164.jpeg",
  "image_165.jpeg",
  "image_166.jpeg",
  "image_167.jpeg",
  "image_168.png",
  "image_169.png",
  "image_170.png",
  "image_171.png",
  "image_172.jpeg",
  "image_174.jpeg",
  "image_176.jpeg",
  "image_177.jpeg",
  "image_178.jpeg",
  "image_179.jpeg",
  "image_180.jpeg",
  "image_182.jpeg",
  "image_195.jpeg",
  "image_196.jpeg",
  "image_198.jpeg",
  "image_201.jpeg",
];

const LABELS = ["Art", "Design", "Visual", "Work"];

function buildColumns(images, columnCount) {
  const columns = Array.from({ length: columnCount }, () => []);
  const baseSize = Math.floor(images.length / columnCount);
  const remainder = images.length % columnCount;
  let imageIndex = 0;

  for (let columnIndex = 0; columnIndex < columnCount; columnIndex++) {
    const columnSize = baseSize + (columnIndex < remainder ? 1 : 0);

    for (let offset = 0; offset < columnSize; offset++) {
      const fileName = images[imageIndex++];
      columns[columnIndex].push({
        src: `artfolio_images/${fileName}`,
        label: LABELS[(imageIndex - 1) % LABELS.length],
      });
    }
  }

  return columns;
}

>>>>>>> 3d298d52b34ddf50ea7a8db1527ad030fdb99e52
const COLUMN_IMAGES = buildColumns(GALLERY_IMAGES, 3);